server:
  port: ${SERVER_PORT:8092}

spring:
  datasource:
    url: ${HOTEL_DB_URL:jdbc:h2:mem:propertyview}
    username: ${HOTEL_DB_USERNAME:sa}
    password: ${HOTEL_DB_PASSWORD:sa}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show_sql: false
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log-path: classpath:changelog/db.changelog-master.yaml
    enabled: true